#!/usr/bin/env python3
"""Measure strict 1-hop Graphiti expansion containment without graph writes."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import statistics
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any


DEFAULT_CONTAINER = "memory-server-neo4j-1"
DEFAULT_LOG = "/home/justin/.hermes/state/recall-log.snapshot-20260831.jsonl"
DEFAULT_GROUP = "mnemos"
CAPS: tuple[int | None, ...] = (10, 25, 50, 100, None)
TOP_KS = (2, 3, 5, 8)
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
FORBIDDEN_CYPHER = re.compile(
    r"\b(?:CREATE|MERGE|SET|DELETE|DETACH|REMOVE|DROP|LOAD\s+CSV|FOREACH|CALL)\b",
    re.IGNORECASE,
)
TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9._/-]{1,}|[가-힣]{2,}")

SAMPLE_ROWS: dict[int, str] = {
    4: "claude-lb completion; concise project-status query",
    13: "Discord projects post; distinct channel-management topic",
    18: "claude-lb M1 scope; milestone/planning topic",
    33: "Anthropic Team/API key; account/authentication topic",
    41: "Sharadar subscription; finance/data-vendor topic",
    59: "delete one M1 plan line; narrow document-edit intent",
    92: "completed work/test debt; delegation/status topic",
    94: "approved numbered tasks; memory-plugin deployment topic",
    95: "memory-health watchdog; cron/heartbeat topic",
    96: "Codex test-only delegation; constrained validation topic",
    98: "M3 gate auto-reset; milestone/reproduction topic",
    104: "Graphiti upstream PR; contribution topic",
    105: "what was item 2; continuity query with sparse wording",
    107: "continue approved work; contextual query from another channel",
    111: "short approval continuation; contextual ambiguity stress case",
    115: "very short GD query; minimal-vocabulary stress case",
    120: "Instagram Reels history; social-media history topic",
    121: "persist Reels history; ingestion/design topic",
}

STOPWORDS = {
    "the", "and", "for", "with", "from", "this", "that", "what", "was",
    "were", "how", "into", "via", "use", "using", "message", "session",
    "scope", "recent", "topics", "triggering", "reply", "react", "pin",
    "id", "current", "work", "orders", "project", "projects", "그렇게",
    "작업", "진행", "해줘", "어떻게", "우리", "현재", "있는", "했던",
    "뭐였더라", "완료", "관련", "부분", "위해서", "하려면", "좋을까",
}


def run(command: list[str]) -> str:
    completed = subprocess.run(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode:
        raise RuntimeError(
            f"command failed ({completed.returncode}): {command!r}\n"
            f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
        )
    return completed.stdout


def load_rows(path: Path) -> tuple[list[dict[str, Any]], str]:
    raw = path.read_bytes()
    rows = [json.loads(line) for line in raw.decode("utf-8").splitlines() if line.strip()]
    if len(rows) != 126:
        raise ValueError(f"expected frozen 126-row snapshot, found {len(rows)}")
    return rows, hashlib.sha256(raw).hexdigest()


def select_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    selected = []
    for row_number, reason in SAMPLE_ROWS.items():
        row = rows[row_number - 1]
        edges = row.get("edges", [])
        if not 1 <= len(edges) <= 3:
            raise ValueError(f"row {row_number}: expected 1-3 edges, got {len(edges)}")
        if any(not UUID_RE.fullmatch(edge) for edge in edges):
            raise ValueError(f"row {row_number}: invalid edge UUID")
        selected.append(
            {
                "row_number": row_number,
                "selection_reason": reason,
                "at": row.get("at"),
                "query": row.get("query", ""),
                "edges": edges,
            }
        )
    return selected


def cypher_for(edge_ids: list[str], group_id: str) -> str:
    if any(not UUID_RE.fullmatch(edge_id) for edge_id in edge_ids):
        raise ValueError("edge IDs must be lowercase UUIDs")
    if not re.fullmatch(r"[A-Za-z0-9_-]+", group_id):
        raise ValueError("group ID contains unsupported characters")
    ids = json.dumps(edge_ids, ensure_ascii=True)
    group = json.dumps(group_id, ensure_ascii=True)
    return f"""// Generated by containment_harness.py. Read-only by construction.
MATCH (base_source)-[base:RELATES_TO]->(base_target)
WHERE base.uuid IN {ids} AND base.group_id = {group}
WITH {ids} AS baseline_ids,
     collect(DISTINCT base.uuid) AS found_baseline_ids,
     collect(base_source) + collect(base_target) AS raw_anchors
UNWIND raw_anchors AS anchor
WITH baseline_ids, found_baseline_ids, collect(DISTINCT anchor) AS anchors
UNWIND anchors AS anchor
OPTIONAL MATCH (anchor)-[degree_edge:RELATES_TO]-()
WHERE degree_edge.group_id = {group} AND degree_edge.invalid_at IS NULL
WITH baseline_ids, found_baseline_ids, anchors, anchor,
     count(DISTINCT degree_edge) AS endpoint_degree
WITH baseline_ids, found_baseline_ids,
     collect({{
       node: anchor,
       uuid: anchor.uuid,
       name: anchor.name,
       degree: endpoint_degree
     }}) AS anchor_info
UNWIND anchor_info AS anchor_item
WITH baseline_ids, found_baseline_ids, anchor_info, anchor_item,
     anchor_item.node AS anchor
OPTIONAL MATCH (anchor)-[candidate:RELATES_TO]-(other)
WHERE candidate.group_id = {group}
  AND candidate.invalid_at IS NULL
  AND NOT candidate.uuid IN baseline_ids
WITH found_baseline_ids, anchor_info, candidate,
     collect(DISTINCT {{
       uuid: anchor_item.uuid,
       name: anchor_item.name,
       degree: anchor_item.degree
     }}) AS candidate_anchors
WITH found_baseline_ids, anchor_info,
     collect(CASE WHEN candidate IS NULL THEN null ELSE {{
       uuid: candidate.uuid,
       relation_type: candidate.name,
       fact: candidate.fact,
       source: {{uuid: startNode(candidate).uuid, name: startNode(candidate).name}},
       target: {{uuid: endNode(candidate).uuid, name: endNode(candidate).name}},
       anchors: candidate_anchors
     }} END) AS raw_candidates
RETURN apoc.text.base64Encode(apoc.convert.toJson({{
  kind: 'hop1_containment',
  found_baseline_ids: found_baseline_ids,
  endpoints: [item IN anchor_info | {{
    uuid: item.uuid,
    name: item.name,
    degree: item.degree
  }}],
  candidates: [item IN raw_candidates WHERE item IS NOT NULL]
}})) AS json_base64;
"""


def assert_read_only(cypher: str) -> None:
    match = FORBIDDEN_CYPHER.search(cypher)
    if match:
        raise ValueError(f"refusing forbidden Cypher token: {match.group(0)}")
    statements = [part.strip() for part in cypher.split(";") if part.strip()]
    if len(statements) != 1:
        raise ValueError(f"expected one read statement, found {len(statements)}")
    statement = re.sub(r"(?m)^\s*//.*$", "", statements[0]).strip()
    if not statement.upper().startswith("MATCH ") or not statement.upper().endswith("AS JSON_BASE64"):
        raise ValueError("query must start with MATCH and end with RETURN payload")


def parse_plain_json(stdout: str) -> dict[str, Any]:
    decoded = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line.startswith('"'):
            continue
        encoded = json.loads(line)
        value = json.loads(base64.b64decode(encoded).decode("utf-8"))
        if isinstance(value, dict) and value.get("kind") == "hop1_containment":
            decoded.append(value)
    if len(decoded) != 1:
        raise ValueError(f"expected one JSON result row, found {len(decoded)}")
    return decoded[0]


def run_cypher(cypher: str, container: str, row_number: int) -> dict[str, Any]:
    assert_read_only(cypher)
    container_path = f"/tmp/m3-containment-row-{row_number:03d}.cypher"
    with tempfile.TemporaryDirectory(prefix="m3-containment-") as temp_dir:
        staged_path = Path(temp_dir) / f"row-{row_number:03d}.cypher"
        staged_path.write_text(cypher, encoding="utf-8")
        run(["docker", "cp", str(staged_path), f"{container}:{container_path}"])
    inside = (
        '/var/lib/neo4j/bin/cypher-shell -u "${NEO4J_AUTH%%/*}" '
        f'-p "${{NEO4J_AUTH#*/}}" --format plain -f {container_path}'
    )
    started = time.perf_counter()
    stdout = run(["docker", "exec", container, "sh", "-c", inside])
    elapsed_ms = (time.perf_counter() - started) * 1000
    result = parse_plain_json(stdout)
    result["latency_ms"] = elapsed_ms
    result["generated_cypher"] = cypher
    return result


def clean_query(query: str) -> str:
    match = re.search(r"\[최근원\]\s*(.*?)(?:\nSession scope:|$)", query, re.DOTALL)
    if match:
        return match.group(1).strip()
    return re.split(r"\nSession scope:", query, maxsplit=1)[0].strip()


def tokens(text: str) -> set[str]:
    return {
        token.lower().strip("._/-")
        for token in TOKEN_RE.findall(text)
        if len(token.lower().strip("._/-")) >= 2
        and token.lower().strip("._/-") not in STOPWORDS
    }


def annotate_candidates(row: dict[str, Any], raw: dict[str, Any]) -> list[dict[str, Any]]:
    query_tokens = tokens(clean_query(row["query"]))
    candidates = []
    for candidate in raw["candidates"]:
        candidate_text = " ".join(
            str(value or "")
            for value in (
                candidate.get("fact"),
                candidate.get("relation_type"),
                candidate.get("source", {}).get("name"),
                candidate.get("target", {}).get("name"),
            )
        )
        overlap = sorted(query_tokens & tokens(candidate_text))
        item = dict(candidate)
        item["anchors"] = sorted(candidate["anchors"], key=lambda anchor: anchor["uuid"])
        item["lexical_overlap_tokens"] = overlap
        item["same_anchor_node"] = bool(item["anchors"])
        item["earlier_heuristic_related"] = bool(overlap) or item["same_anchor_node"]
        candidates.append(item)
    return sorted(candidates, key=lambda item: item["uuid"])


def cap_label(cap: int | None) -> str:
    return "none" if cap is None else str(cap)


def select_configuration(
    candidates: list[dict[str, Any]], cap: int | None, top_k: int | None
) -> list[dict[str, Any]]:
    eligible = []
    for candidate in candidates:
        anchors = [
            anchor for anchor in candidate["anchors"]
            if cap is None or anchor["degree"] <= cap
        ]
        if not anchors:
            continue
        item = dict(candidate)
        item["eligible_anchors"] = anchors
        item["shared_anchor_count"] = len(anchors)
        item["min_endpoint_degree"] = min(anchor["degree"] for anchor in anchors)
        eligible.append(item)
    eligible.sort(
        key=lambda item: (
            -item["shared_anchor_count"],
            item["min_endpoint_degree"],
            item["uuid"],
        )
    )
    return eligible if top_k is None else eligible[:top_k]


def distribution(values: list[float]) -> dict[str, float]:
    return {
        "min": min(values),
        "median": statistics.median(values),
        "max": max(values),
    }


def summarize_configuration(
    per_row: list[dict[str, Any]], cap: int | None, top_k: int | None, baseline_total: int
) -> dict[str, Any]:
    row_counts = []
    earlier_noise = []
    lexical_noise = []
    for row in per_row:
        selected = select_configuration(row["candidates"], cap, top_k)
        total = len(selected)
        row_counts.append({"row_number": row["row_number"], "candidate_count": total})
        earlier_unrelated = sum(not item["earlier_heuristic_related"] for item in selected)
        lexical_unrelated = sum(not item["lexical_overlap_tokens"] for item in selected)
        earlier_noise.append(earlier_unrelated / total if total else 0.0)
        lexical_noise.append(lexical_unrelated / total if total else 0.0)
    total_candidates = sum(item["candidate_count"] for item in row_counts)
    return {
        "max_endpoint_degree": cap_label(cap),
        "top_k_per_row": top_k if top_k is not None else "none",
        "total_candidates": total_candidates,
        "fan_out_ratio": total_candidates / baseline_total,
        "earlier_noise_proxy_distribution": distribution(earlier_noise),
        "lexical_only_noise_proxy_distribution": distribution(lexical_noise),
        "per_row_counts": row_counts,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--container", default=DEFAULT_CONTAINER)
    parser.add_argument("--recall-log", type=Path, default=Path(DEFAULT_LOG))
    parser.add_argument("--group-id", default=DEFAULT_GROUP)
    parser.add_argument("--output-dir", type=Path, default=Path("spike/raw"))
    parser.add_argument("--reuse-raw", action="store_true")
    args = parser.parse_args()

    rows, snapshot_sha256 = load_rows(args.recall_log)
    selected = select_rows(rows)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    selection_document = {
        "source": str(args.recall_log),
        "source_row_count": len(rows),
        "source_sha256": snapshot_sha256,
        "selection_note": "Reused the exact fixed 18-row sample recorded by the first attempt.",
        "selected": selected,
    }
    (args.output_dir / "containment-selected-rows.json").write_text(
        json.dumps(selection_document, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    per_row = []
    for row in selected:
        raw_path = args.output_dir / f"containment-row-{row['row_number']:03d}.json"
        if args.reuse_raw:
            raw = json.loads(raw_path.read_text(encoding="utf-8"))
        else:
            cypher = cypher_for(row["edges"], args.group_id)
            raw = run_cypher(cypher, args.container, row["row_number"])
            if set(raw["found_baseline_ids"]) != set(row["edges"]):
                raise ValueError(
                    f"row {row['row_number']}: baseline mismatch "
                    f"{raw['found_baseline_ids']} != {row['edges']}"
                )
            raw_path.write_text(
                json.dumps(raw, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        candidates = annotate_candidates(row, raw)
        per_row.append(
            {
                "row_number": row["row_number"],
                "baseline_edge_count": len(row["edges"]),
                "endpoint_count": len(raw["endpoints"]),
                "endpoints": sorted(raw["endpoints"], key=lambda item: item["uuid"]),
                "pre_filter_candidate_count": len(candidates),
                "latency_ms": raw["latency_ms"],
                "candidates": candidates,
            }
        )

    baseline_total = sum(row["baseline_edge_count"] for row in per_row)
    configurations = []
    for cap in CAPS:
        configurations.append(summarize_configuration(per_row, cap, None, baseline_total))
        for top_k in TOP_KS:
            configurations.append(summarize_configuration(per_row, cap, top_k, baseline_total))
    pre_filter_total = sum(row["pre_filter_candidate_count"] for row in per_row)
    latencies = [row["latency_ms"] for row in per_row]
    aggregate = {
        "sample_rows": len(per_row),
        "total_baseline_edges": baseline_total,
        "pre_filter_1hop_candidate_total": pre_filter_total,
        "pre_filter_1hop_fan_out_ratio": pre_filter_total / baseline_total,
        "latency_ms_distribution": distribution(latencies),
        "ranking_rule": (
            "shared eligible anchor count descending, then lowest eligible endpoint degree "
            "ascending, then candidate edge UUID ascending"
        ),
        "noise_proxy_note": (
            "The earlier proxy marks a candidate related for query content-word overlap OR "
            "sharing a baseline anchor node. Every strict 1-hop candidate shares such an "
            "anchor, so that proxy is identically zero noise here. lexical_only is reported "
            "as a topical-overlap sensitivity; neither proxy is ground truth."
        ),
        "configurations": configurations,
    }
    (args.output_dir / "containment-measurements.json").write_text(
        json.dumps(per_row, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (args.output_dir / "containment-aggregate.json").write_text(
        json.dumps(aggregate, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(aggregate, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
